server {
    listen 80;
    server_name 89-167-93-204.nip.io app.89-167-93-204.nip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 89-167-93-204.nip.io;

    ssl_certificate /etc/letsencrypt/live/89-167-93-204.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/89-167-93-204.nip.io/privkey.pem;

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl;
    server_name app.89-167-93-204.nip.io;

    ssl_certificate /etc/letsencrypt/live/app.89-167-93-204.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.89-167-93-204.nip.io/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}