"""Add embedding vector column to vacancies

Revision ID: 23f50398c247
Revises: f24f456d5ea0
Create Date: 2026-07-08 11:28:29.668318

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '23f50398c247'
down_revision: Union[str, Sequence[str], None] = 'f24f456d5ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'embedding')
    # ### end Alembic commands ###
