"""apply refactoring: field lengths, timezone-aware dates, ondelete, indexes, updated_at

Revision ID: ade3b59f56d4
Revises: 23f50398c247
Create Date: 2026-07-16 09:09:27.140443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ade3b59f56d4'
down_revision: Union[str, Sequence[str], None] = '23f50398c247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('applications_vacancy_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'vacancies', ['vacancy_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('saved_vacancies', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('saved_vacancies_vacancy_id_fkey'), 'saved_vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'saved_vacancies', 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vacancies', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('vacancies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vacancies', 'parsed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_vacancies_active_source', 'vacancies', ['is_active', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_active_source', table_name='vacancies')
    op.alter_column('vacancies', 'parsed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vacancies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vacancies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'saved_vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('saved_vacancies_vacancy_id_fkey'), 'saved_vacancies', 'vacancies', ['vacancy_id'], ['id'])
    op.alter_column('saved_vacancies', 'saved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_vacancy_id_fkey'), 'applications', 'vacancies', ['vacancy_id'], ['id'])
    op.alter_column('applications', 'applied_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('applications', 'updated_at')
    # ### end Alembic commands ###
