"""Add unique constraints to saved_vacancies and applications

Revision ID: bd3ba32c7580
Revises: 8f7d02fa0ddf
Create Date: 2026-06-30 07:18:31.478289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3ba32c7580'
down_revision: Union[str, Sequence[str], None] = '8f7d02fa0ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_application_vacancy', 'applications', ['user_id', 'vacancy_id'])
    op.create_unique_constraint('uq_user_saved_vacancy', 'saved_vacancies', ['user_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_saved_vacancy', 'saved_vacancies', type_='unique')
    op.drop_constraint('uq_user_application_vacancy', 'applications', type_='unique')
    # ### end Alembic commands ###
