"""Add cascade delete on user_id foreign keys

Revision ID: f24f456d5ea0
Revises: b5eecbdc8485
Create Date: 2026-06-30 11:26:35.270429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24f456d5ea0'
down_revision: Union[str, Sequence[str], None] = 'b5eecbdc8485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('saved_vacancies_user_id_fkey'), 'saved_vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'saved_vacancies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('saved_vacancies_user_id_fkey'), 'saved_vacancies', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
